(function(z){
var yK=function(a,b,c){b="new"===(b||a.nd);return c?(a=a.d.u.v().get(z.U.Ep),b?-1:-a):a.gl+(b?-1:1)};var zK=function(a){z.zv.call(this,a);this.gl=0;this.nd="new"};var AK=function(a,b){a.VX=b};
var BK=function(a){return(0,z.Q)('\x3cdiv class\x3d"fyre '+(a.Kd?"fyre-liveblog ":"")+(a.gh?"fyre-livechat ":"")+(a.pU?"fyre-bootstrap ":"")+(a.re?"fyre-mobile":"")+'"\x3e\x3cdiv class\x3d"fyre-widget '+(a.Ra?"fyre-avatar-disabled":"")+'"\x3e'+(0,z.Q)('\x3cdiv class\x3d"fyre-featured-content-wrapper" style\x3d"display: none"\x3e\x3c/div\x3e')+'\x3cdiv class\x3d"fyre-stream-stats"\x3e\x3cdiv class\x3d"fyre-comment-count"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-help"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-auth"\x3e\x3cdiv class\x3d"fyre-login-bar"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-live-container"\x3e\x3cdiv class\x3d"fyre-livecount"\x3e\x3c/div\x3e'+
(a.Ra?"":'\x3cdiv class\x3d"fyre-listener-avatars"\x3e\x3c/div\x3e')+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-editor"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-input-box-collapsed"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-comment-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-top-content-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-thread-breakout-stream"\x3e\x3c/div\x3e'+(a.qo?'\x3cdiv class\x3d"fyre-archive-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-archive-stream"\x3e\x3c/div\x3e':
"")+'\x3cdiv class\x3d"fyre-stream-menu-container"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e')};var CK=function(a){return(0,z.Q)('\x3ca href\x3d"'+z.R(z.S(a.Aa))+'" title\x3d"'+z.R(a.aa)+'" aria-label\x3d"'+z.R(a.aa)+" "+z.R(a.j.profile)+'" data-id\x3d"'+z.R(a.id)+'" class\x3d"fyre-follower fyre-follower-'+z.R(a.YT)+'"\x3e\x3cimg src\x3d"'+z.R(z.S(a.Uc))+'" alt\x3d"'+z.R(a.aa)+" "+z.R(a.j.Uc)+'" onerror\x3d"javascript:this.src\x3d\''+z.R(z.$o(a.ec))+"';\" /\x3e\x3c/a\x3e")};
var DK=function(a){return(0,z.Q)(z.Zq(a)+'\x3cdiv class\x3d"fyre-archive-stream-sort fyre-stream-sort"\x3e\x3ch3 class\x3d"fyre-archive-stream-title"\x3e\x3cstrong class\x3d"fyre-archive-stream-title-icon"\x3e\x3c/strong\x3e'+z.P(a.j.EO)+'\x3c/h3\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.P(a.j.ey)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(a.j.Vo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.P(a.j.fy)+"\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e")};var EK=function(a){return(0,z.Q)('\x3cdiv class\x3d"tooltip"\x3e'+z.P(a.message)+'\x3c/div\x3e\x3cdiv class\x3d"arrow-down"\x3e\x3c/div\x3e')};var FK=function(){};var GK=function(a){this.LG=!1;this.Lo=[];this.Ab=null;z.xf.call(this,a)};var HK=function(a,b){z.Cj.call(this,b,a)};var IK=function(a,b){z.ZF.call(this,a,b)};
var JK=function(a,b){var c=a.d.Jb;c.th[4]&&(z.vz(c,4,(0,z.t)(function(a){b.e(a,"threadBreakout",this.Nr)},a)),z.xz(c,4,(0,z.t)(function(a){b.Fa(a,"threadBreakout",this.Nr)})))};
var KK=function(a,b){if(!z.lk(b,"fyre-stream-sort-selected")&&"A"===b.tagName&&b!==a.Cg)if(b===a.sl)a.IF();else{LK(a,b);a.rm();z.y(b.parentElement.children,function(a){a.setAttribute("aria-selected",a===b)});var c=null;switch(b){case a.ut:a.rE();c="hottest";break;case a.xz:a.dispatchEvent({type:"sortTopComments",Yb:(0,z.t)(a.Hd,a)});c="top_comments";break;case a.sm:a.un("new");c="newest";break;case a.wz:a.un("old"),c="oldest"}a.d.Lb.send(z.Vn("SortStream",{Ds:c}))}};
var LK=function(a,b){var c=[a.sm,a.wz];a.Cg&&c.push(a.Cg);a.ut&&c.push(a.ut);a.xz&&c.push(a.xz);z.y(c,function(a){z.hk(a,"fyre-stream-sort-selected")});z.fk(b,"fyre-stream-sort-selected")};var MK=function(a,b){z.ZF.call(this,a,b)};var NK=function(a,b){z.Vx.call(this,a,b);this.fh=!1;this.WI=!!this.L.J.NG;this.Ia=new z.dy;this.Ia.tc(this);this.tu="archiveShowMore"};var OK=function(a,b){z.aG.call(this,a,b)};var PK=function(a,b,c){z.eu.call(this,a,b,c);this.Sz=b||"";this.zg(EK(this.s()))};
var QK=function(a,b,c){z.Zt.call(this,a,b||3,c)};var RK=function(a,b){z.T.call(this,b);this.l=a;this.yt=z.W};var SK=function(a,b){z.T.call(this,b);this.Ec=a};var TK=function(a,b){SK.call(this,a,b)};
var UK=function(){var a=z.u.window,b=z.u.document;function c(){var a=x.elements;return"string"==typeof a?a.split(" "):a}function d(a){var b={},d=a.createElement,f=a.createDocumentFragment,g=f();a.createElement=function(a){x.xX||d(a);var c;c=b[a]?b[a].cloneNode():k.test(a)?(b[a]=d(a)).cloneNode():d(a);return c.canHaveChildren&&!h.test(a)?g.appendChild(c):c};a.createDocumentFragment=Function("h,f","return function(){var n\x3df.cloneNode(),c\x3dn.createElement;h.shivMethods\x26\x26("+c().join().replace(/\w+/g,
function(a){b[a]=d(a);g.createElement(a);return'c("'+a+'")'})+");return n}")(x,g)}function f(a){var b;if(a.KP)return a;if(x.wX&&!m){b=a.createElement("p");var c=a.getElementsByTagName("head")[0]||a.documentElement;b.innerHTML="x\x3cstyle\x3earticle,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio{display:none}canvas,video{display:inline-block;*display:inline;*zoom:1}[hidden]{display:none}audio[controls]{display:inline-block;*display:inline;*zoom:1}mark{background:#FF0;color:#000}\x3c/style\x3e";
b=!!c.insertBefore(b.lastChild,c.firstChild)}r||(b=!d(a));b&&(a.KP=b);return a}var g={},h=/^<|^(?:button|form|map|select|textarea|object|iframe)$/i,k=/^<|^(?:a|b|button|code|div|fieldset|form|h1|h2|h3|h4|h5|h6|i|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul)$/i,m,r;(function(){var c=b.createElement("a");c.innerHTML="\x3cxyz\x3e\x3c/xyz\x3e";(m="hidden"in c)&&"function"==typeof a.kU&&a.kU("#modernizr{}",function(b){b.hidden=
!0;m="none"==(a.getComputedStyle?a.getComputedStyle(b,null):b.currentStyle).display});r=1==c.childNodes.length||function(){try{b.createElement("a")}catch(a){return!0}var c=b.createDocumentFragment();return"undefined"==typeof c.cloneNode||"undefined"==typeof c.createDocumentFragment||"undefined"==typeof c.createElement}()})();var x={elements:g.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",
shivCSS:!1!==g.wX,shivMethods:!1!==g.xX,type:"default",shivDocument:f};f(b)};var VK=function(a,b){z.kG.call(this,a,b);a.J.EP||UK();var c=a.u.Dc(),d=a.u.v();this.oi=new z.cG(a,a.Sl.ya,d.gh()||z.Xf);this.D(this.oi);a.J.Ra||(this.Fn=new TK(c),this.D(this.Fn));this.Vr=new z.bG;this.D(this.Vr)};var WK=function(a){var b=z.F.eb()||z.F.get(z.E.Gp);return!a.w.Kd()||b};var XK=function(a){z.qG.call(this,a);this.Xm=1};
var YK=function(a){z.Rs.call(this,a);z.ev(a.u);this.Tb=new VK(a);this.Yq.start();this.Il(this.Tb);z.Ws(this)};var ZK=function(a,b){this.eD=HK;this.WJ=YK;z.W.nm(b.strings||{});z.Fn.call(this,a,b);this.Ya.Lb.send(z.Vn("Init"))};var $K=function(a){a.pk&&(a.pk.q(),delete a.pk)};z.v(zK,z.zv);z.e=zK.prototype;z.e.tl=z.l(57);z.e.LF=z.l(59);z.e.MF=z.l(58);z.e.LF=z.L(59,function(a){this.La||(this.Ho[a]=!1,z.Av(this,a,function(a){a.N(a.Ca.Wm)}))});
z.e.MF=z.L(58,function(a,b){if(!this.La){var c=this.d.u.v(),d=z.Ou(a,b),f=c.get(z.U.Qt);c.set(z.U.Ep,d.DV);z.A(d.gb,(0,z.t)(this.d.U.N,this.d.U,"bootstrap_author_received"));d.content=z.ej(d.content,function(a,b){return!z.Ua(f,b)});z.A(d.content,function(a){z.kb(d.content,z.Cv(this,a))},this);z.kb(this.sc,z.dj(d.content,z.Bb(a)));this.ae(a,d.content);z.Av(this,a,function(b){b.N(b.Ca.Gk,{Od:a});b.set(b.k.qf,!0)})}});
z.e.tl=z.L(57,function(a,b){this.gl=a;this.nd=b||this.nd;var c=this.Pd[a]=new z.vv;z.Eu.C();var d=this.d.u.v(),f=(0,z.t)(this.MF,this,a),g=(0,z.t)(this.LF,this,a),h=this.d.J.an,d=d.get(z.U.xc),h=z.w.Yu(d,h)+String(a)+".json";z.Fu(0,h,f,g);return c});z.Xv.prototype.tl=z.L(56,function(a,b){this.Sk||(this.Sk=new zK(this.L));var c=this.Sk,d=yK(c,a,b);return c.tl(d,a)});z.Eu.prototype.Vh=z.L(50,function(a,b,c){a=z.wa("%s%scollection/%s/hot/",z.w.H.Bd,z.w.lf,a.ta);(new z.Ie({url:a,ua:b,oa:c})).send()});
z.Qv.prototype.Vh=z.L(49,function(a){var b={ta:this.d.u.v().id},c=z.Eu.C().Vh;z.Rv(this,c,b,a);return a});z.Xv.prototype.Vh=z.L(48,function(){z.Wv(this);this.Oi=new z.Qv(this.L,void 0);var a=new z.vv;this.Oi.Vh(a);return a});z.Eu.prototype.Rh=z.L(47,function(a,b,c){a=z.wa("%s%scollection/%s/top/%s/",z.w.H.Bd,z.w.lf,a.ta,a.xO);(new z.Ie({url:a,ua:b,oa:c})).send({format:"stream"})});z.Qv.prototype.Rh=z.L(46,function(a,b){var c={ta:this.d.u.v().id,xO:a},d=z.Eu.C().Rh;z.Rv(this,d,c,b);return b});
z.Xv.prototype.Rh=z.L(45,function(a){z.Wv(this);this.Oi=new z.Qv(this.L,void 0);var b=new z.vv;this.Oi.Rh(a,b);return b});z.T.prototype.ZG=z.L(44,function(){return this.ba});z.zj.prototype.qo=z.L(43,function(){return this.get(this.k.Dp)});z.v(FK,z.Ln);z.ca(FK);var aL={dZ:"attachmentDelegate"};z.kb(aL,z.fH);FK.prototype.no=function(a){var b=FK.b.no.call(this,a),c=a.attachmentDelegate;c&&(b.GO=c);b.Yx=a[aL.fM]||null;return b};z.v(GK,z.xf);GK.prototype.MU=function(a){this.Ab||(this.Ab=z.u.setInterval((0,z.t)(this.GQ,this),5E3));this.Lo=this.Lo.concat(a)};
GK.prototype.GQ=function(){this.Lo.length&&(this.LG||(z.dg("//platform.twitter.com/impressions.js"),this.LG=!0),z.u.twttr=function(){var a=z.u.twttr||{},b=a.impressions||{};b._e=b._e||[];b.ready=b.ready||function(a){b._e.push(a)};a.impressions=b;return a}(),z.u.twttr.impressions.ready((0,z.t)(function(a){a.impressions.logTweets(this.Lo,{partner:"livefyre"});this.Lo=[]},this)))};GK.prototype.q=function(){(0,window.clearInterval)(this.Ab);GK.b.q.call(this)};z.v(HK,z.Cj);HK.prototype.gz=function(a){this.Fu=new z.Pq(this,a);this.Lb=new z.Nn(this);this.Jc=new z.ri(this);this.u=new z.bv(this,a);this.jb=new z.nv(this,a);this.Mb=new z.Xv(this,a);this.Sl=new z.bw(this);new z.hf;this.ap=new z.Cw(this,a);this.Ez=new z.cw(this);this.Ji=new z.rw(this);this.Tz=new z.Gu(this,a);this.rY=new GK(this);this.Jb=new z.lz(this)};z.v(IK,z.ZF);z.e=IK.prototype;z.e.s=function(){var a={},b=this.d.u,c=b.v();a.Tx=b.v().Kd();a.AV=!z.F.get(z.F.k.Wd);a.Jd=b.Jd(z.F.id);a.HP=2===c.get(z.U.bj);a.GP=3===c.get(z.U.bj);a.j={FU:z.W.get(z.W.g.hu),IU:z.W.get(z.W.g.iu),WT:z.W.get(z.W.g.lB),ey:z.W.get(z.W.g.Zp),fy:z.W.get(z.W.g.$p),Vo:z.W.get(z.W.g.mC),kp:z.W.get(z.W.g.dq),jY:z.W.get(z.W.g.DC)};return a};
z.e.K=function(a){IK.b.K.call(this,a);a=this.c;var b;b=this.s();var c=z.Q,d=z.Zq(b),f;f=b.Tx?(0,z.Q)('\x3ca class\x3d"fyre-follow-conversation"\x3e'+(b.AV?b.Jd?z.P(b.j.IU):z.P(b.j.FU):"")+"\x3c/a\x3e"):"";b=c(d+f+'\x3cdiv class\x3d"fyre-stream-sort"\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected" aria-selected\x3d"true" aria-label\x3d"Sort by Newest" tabindex\x3d"0"\x3e'+z.P(b.j.ey)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+
z.P(b.j.Vo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest" aria-selected\x3d"false" aria-label\x3d"Sort by Oldest" tabindex\x3d"0"\x3e'+z.P(b.j.fy)+"\x3c/a\x3e"+(b.HP?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(b.j.Vo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-top-comments" aria-selected\x3d"false" aria-label\x3d"Sort by Top Comments" tabindex\x3d"0"\x3e'+z.P(b.j.jY)+"\x3c/a\x3e":"")+(b.GP?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(b.j.Vo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-hot-threads" aria-selected\x3d"false" aria-label\x3d"Sort by Hot Threads" tabindex\x3d"0"\x3e'+
z.P(b.j.WT)+"\x3c/a\x3e":"")+'\x3c/div\x3e\x3ca class\x3d"fyre-stream-sort-back"\x3e\x3c/a\x3e\x3c/div\x3e');a.innerHTML=b;this.sl=this.o("fyre-follow-conversation");this.ut=this.o("fyre-stream-sort-hot-threads")||null;this.xz=this.o("fyre-stream-sort-top-comments")||null;this.Cg=this.o("fyre-stream-sort-back");this.sm=this.o("fyre-stream-sort-newest");this.wz=this.o("fyre-stream-sort-oldest");this.aJ=this.o("fyre-stream-sort-options");this.cd=this.o("fyre-content-loading");this.Hd()};
z.e.m=function(){IK.b.m.call(this);var a=this.p();z.F.on(z.F.Ca.Wf,this.fo,this);a.e(this.c,"click",this.lb);a.e(this.c,"keydown",this.rS);z.y([3,4,5],function(b){z.$F(this,a,b)},this);JK(this,a)};z.e.lb=function(a){a.preventDefault();KK(this,a.target)};z.e.rS=function(a){if(13===a.keyCode||32===a.keyCode)a.preventDefault(),KK(this,a.target)};z.e.Gi=function(a,b){a&&this.hz(b);z.xl(this.aJ,"display",a?"none":"block");z.xl(this.Cg,"display",a?"block":"none")};
z.e.hz=function(a){var b=this.sm,c=this.un,d=z.W.get(z.W.g.Rt);4===a&&(b=this.ut,c=this.rE,d=z.W.get(z.W.g.jK));this.Cg.innerHTML=d;this.p().Ld(this.Cg,"click",(0,z.t)(function(a){a.stopPropagation();this.Gi(!1);LK(this,b);c.apply(this)},this))};z.e.ao=function(a){a.stopPropagation();this.Gi(!1);LK(this,this.sm);this.un()};z.e.Nr=function(a){var b=a.Yb;z.kb(a,{Yb:(0,z.t)(function(){b();this.Gi(!0,4)},this)})};
z.e.un=function(a){this.dispatchEvent({type:"sortOrderChanged",direction:a||"new",Yb:(0,z.t)(this.Hd,this)})};z.e.rE=function(){this.dispatchEvent({type:"sortHotThreads",Yb:(0,z.t)(this.Hd,this)})};z.e.IF=function(){var a=this.d.u;a.v();var b=z.F.k;z.F.id?(b=a.Jd(z.F.get(b.X)),a.Aj(!b),a=b?z.W.get(z.W.g.hu):z.W.get(z.W.g.iu),this.sl.innerHTML=a):z.Mh(this.d.Jc,(0,z.t)(this.IF,this))};
z.e.fo=function(){var a=this.d.u,b=a.v(),c=z.F.k,b=!b.Kd()||z.F.get(c.Wd);this.sl&&(b?z.N(this.sl,!1):(a=a.Jd(z.F.id)?z.W.get(z.W.g.iu):z.W.get(z.W.g.hu),this.sl.innerHTML=a,z.N(this.sl,!0)))};z.e.h=function(){IK.b.h.call(this);z.F.off(null,null,this)};z.v(MK,IK);MK.prototype.K=function(a){this.c=a;z.ro(a,DK,this.s());this.sm=this.o("fyre-stream-sort-newest");this.wz=this.o("fyre-stream-sort-oldest");this.aJ=this.o("fyre-stream-sort-options");this.cd=this.o("fyre-content-loading");this.Hd()};MK.prototype.un=function(a){this.dispatchEvent({type:"archiveSortOrderChanged",stream:this.VX.stream,direction:a,Yb:(0,z.t)(this.Hd,this)})};
MK.prototype.s=function(){return{j:{EO:z.W.get(z.W.g.dK),ey:z.W.get(z.W.g.Zp),fy:z.W.get(z.W.g.$p),Vo:z.W.get(z.W.g.mC),kp:z.W.get(z.W.g.dq)}}};z.v(NK,z.Vx);z.e=NK.prototype;z.e.jn=function(a){this.clear();z.N(this.c,!0);this.nd=a};z.e.clear=function(){this.ld.Lf();this.vb={};this.Ij=[];for(this.uh=this.Wk=null;this.ma&&0!=this.ma.length;)this.Oo(0).q()};z.e.K=function(a){NK.b.K.call(this,a);z.ro(this.c,z.$q,this.s());this.ik=this.o("fyre-stream-content");this.Hi=this.o("fyre-stream-more");this.Ia.S(this.Hi);z.N(this.Hi,!1)};z.e.h=function(){this.Ia&&this.Ia.q();this.Ia=null;NK.b.h.call(this)};
z.e.m=function(){NK.b.m.call(this);this.p().e(this.Ia,"showMore",this.dx)};z.e.gw=function(){return this.L.J.NG};z.e.s=function(){return{be:z.w.H.ub,wv:!!this.Ia,j:{oz:z.W.get(z.W.g.eK)}}};z.e.ex=function(){this.Ia.qt();this.fh=!0};z.e.uy=function(){this.dispatchEvent({type:this.tu,direction:this.nd,target:this,AY:this.fh&&this.WI,Yb:(0,z.t)(this.ex,this),zj:(0,z.t)(this.lG,this)});this.fh&&(this.WI=!1)};z.e.By=function(a){this.fh||NK.b.By.call(this,a)};
z.e.$o=function(){var a=this.L.Mb.Sk,b=this.nd,c=a.d.u.v(),b="old"===b,c=c.get(z.U.Ep),c=!b&&a.gl>-c;b&&-1>a.gl||c?this.Ia.show():this.Ia.pb()};z.e.start=function(){this.fh||this.uy()};z.v(OK,z.aG);var bL=z.W.g,cL={};cL.comment=[bL.Sm,bL.Xf,bL.Hm];cL.liveblog=[bL.JM,bL.UL,bL.rB];OK.prototype.eF=function(a){function b(a){return z.Ha(a,"%s")?a:"%s "+a}var c=this.l.Kd()?"liveblog":"comment",c=cL[c];switch(a){case 1:c=b(z.W.get(c[1]));break;case 0:if(z.W.get(c[0])!==z.YF[c[0]]){c=z.W.get(c[0]);break}default:c=b(z.W.get(c[2]))}return z.wa(c,a)};z.v(PK,z.eu);PK.prototype.cp=200;PK.prototype.Xh=function(){return new QK(this.Ic)};PK.prototype.s=function(){var a={};a.message=this.Sz;return a};z.v(QK,z.Zt);QK.prototype.Pc=function(a,b,c){var d=z.Wl(this.element),d=new z.yh(d.width,d.height+25);b=z.Ut(this.element,this.Lh,a,b,d,c,9);z.Dl(a.lastChild,0);b&&(d=new z.yh(0,-5),z.Ut(this.element,2,a,1,d,c,5),z.Dl(a.lastChild,a.offsetWidth-(this.element.offsetParent.offsetWidth-this.element.offsetLeft+this.element.offsetWidth/2)))};z.v(RK,z.T);z.e=RK.prototype;z.e.r=function(){this.c=z.uo(CK,this.s())};z.e.m=function(){RK.b.m.call(this);this.Xa=new PK(this.c,this.l.get("displayName"));this.p().e(this.c,"click",this.lb)};z.e.h=function(){RK.b.h.call(this);this.Xa&&this.Xa.q()};z.e.s=function(){var a=z.Od,b=this.yt,c={};c.Uc=this.l.get(a.xb);c.ec=this.l.get(a.vk);c.aa=this.l.get(a.va);c.id=this.l.id;c.YT=this.l.id.replace(/[@.]/g,"-");c.Aa=this.l.get(a.ac);c.j={profile:b.get(b.g.RL),Uc:b.get(b.g.PL)};return c};
z.e.lb=function(a){a.preventDefault();a.stopPropagation();this.dispatchEvent({t:this.l,type:"author_click"})};z.v(SK,z.T);z.e=SK.prototype;z.e.vB=10;z.e.h=function(){SK.b.h.call(this);delete this.Ec};z.e.R=function(){SK.b.R.call(this);this.Ec.off(null,null,this)};z.e.sF=function(a){a=new RK(a);var b=this.Nc();if(b===this.vB){var c=this.Oo(b-1);c&&(c.q(),b--)}0<b?this.Fe(a,0,!0):this.D(a,!0)};z.e.bT=function(a){var b;this.Mc(function(c){a.id===c.l.id&&(b=c)});b&&(this.removeChild(b),b.q())};
z.e.bo=function(){this.Ec.on(this.Ec.Ca.Pt,this.sF,this);this.Ec.on(this.Ec.Ca.pu,this.bT,this);var a=this.Ec.ib.reverse().slice(0,this.vB);z.y(a,this.sF,this)};z.v(TK,SK);z.v(VK,z.kG);
VK.prototype.qI=function(a,b){if(!this.La){this.w=b;var c=b.get(z.U.Ch),d=b.get(z.U.Yd);this.Jt=new z.hG(c,d,a.J.Ra);this.D(this.Jt);this.Jq=new OK(a.u.v());this.D(this.Jq);this.zs=null;b.qo()&&(this.Qu=new MK(a),this.D(this.Qu),this.Tk=new NK(a),this.D(this.Tk),AK(this.Qu,{stream:this.Tk}));this.rh=new IK(a);this.D(this.rh);this.rs((0,z.t)(function(a){this.Ub=a;this.D(this.Ub);a=this.Ub;this.ba&&a&&a.S(this.je,!0)},this));b.get(z.U.Nm)&&!z.Xf&&this.w.er()&&(this.w.gh()||this.w.Kd()||this.Jw())}};
VK.prototype.s=function(){return{Ra:this.d.J.Ra,gh:this.w.gh(),Kd:this.w.Kd(),re:z.Xf,pU:this.d.J.oD,qo:this.w.qo()}};z.jy={$Y:"fyre-archive-stream",aZ:"fyre-archive-stream-header",S1:"fyre-top-content-stream",l2:"fyre-widget",Nm:"fyre-featured-content-wrapper"};z.kb(z.jy,z.eK);z.e=VK.prototype;
z.e.r=function(){this.c=z.uo(BK,this.s());var a=this.w.get(z.U.bj);if(1!==a){var b=this.d.Jb,a=2===a?3:4,c=this.o("fyre-top-content-stream");z.mz(b,a,c,this)}this.Vr.S(this.o(z.jy.DL));this.Tk&&(b=this.o("fyre-archive-stream-header"),this.Qu.S(b),this.Tk.S(this.o("fyre-archive-stream")));this.Mh(1);this.je=this.o(z.jy.zh);b=WK(this);z.N(this.je,b)};
z.e.m=function(){VK.b.m.call(this);var a=this.Ub;this.ba&&a&&a.S(this.je,!0);this.d.U.mp("stream_data_received",this.cS,this);this.p().e(this,"request_content_context",this.AR).e(this,"request_content_reply",this.eT);this.Tk&&this.Tk.start()};z.e.bo=function(){this.Fn&&this.Fn.bo()};z.e.cS=function(){var a=this.w,b=a.get(z.U.zk);z.ph||b||(b=(0,z.t)(function(){this.zs=new z.dL(this.d,a.get(z.U.Yd));this.D(this.zs,!0)},this),z.dg(z.w.H.ub+z.w.kh.zs,null,null,b))};
z.e.Jw=function(){var a=new z.QE(this.ZG,this);a.QH=(0,z.t)(this.TW,this);var b=(0,z.t)(function(){a.start(0,2E3)},this);z.dg(z.w.H.ub+z.w.kh.lQ,null,null,b)};z.e.TW=function(){var a=this.o("fyre-featured-content-wrapper");this.Qv=new z.uK(this.d);this.D(this.Qv);this.Qv.S(a);this.Qv.eh()};z.e.rs=function(a){if(!this.d.J.readOnly){var b=this.d.u.v();z.Yw(z.Vw.C(),"main",a,{L:this.d,zi:"new"},b);z.F.on(z.F.mc(z.F.k.X),this.Yc,this)}};z.e.Yc=function(){if(this.je){var a=WK(this);z.N(this.je,a)}};
z.e.bi=function(){0<z.Bp(this,this.Ub)&&(this.removeChild(this.Ub),this.Ub.q());this.rs((0,z.t)(function(a){this.Ub=a;this.D(this.Ub);a=this.Ub;this.ba&&a&&a.S(this.je,!0);z.N(this.je,!0)},this))};z.e.dh=function(a,b){null!=a&&(this.d.Jb.xl(1),(0,window.setTimeout)((0,z.t)(function(){var c=b&&function(a){z.Uw(a.Qa)};this.La||z.lG(this,a,c)},this),3E3))};z.e.AR=function(a){z.lG(this,a.Zk)};z.e.eT=function(a){z.lG(this,a.Zk,function(a){z.Uw(a.Qa)})};
z.e.h=function(){VK.b.h.call(this);z.F.off(z.F.mc(z.F.k.X),this.Yc,this);this.w&&(this.w.off(null,null,this),this.w=null)};z.v(XK,z.qG);z.e=XK.prototype;z.e.oe=function(a,b){XK.b.oe.call(this,a,b);a.e(b,"repliesExpanded",this.FF);a.e(b,"sortHotThreads",this.pT);a.e(b,"sortOrderChanged",this.oG);a.e(b,"sortTopComments",this.qT);a.e(b,"archiveShowMore",this.jR);a.e(b,"archiveSortOrderChanged",this.kR)};
z.e.jR=function(a){var b=a.Yb||z.n,c=(0,z.t)(this.Te,this,a.target),d=this.d.Mb;a=a.AY;d.Sk||(d.Sk=new zK(d.L));d=d.Sk;a=a?d.gl:yK(d);var f=d.dd[a];f&&(d.gl=a);if(f)b(),c(f);else{d=this.d.Mb.tl();a=d.k.qf;if(d.get(a))b();else d.on(d.mc(a),b,this);z.rG(this,d,c)}};z.e.Ew=function(a,b){var c=2===b.ed,d=1!==b.ed;switch(b.type){case 0:var f=this.d.u.v(),f=z.Hm(b,f),g=f.get(z.Um),g=this.d.u.gb().get(g);f.set(z.Im,g);a.Vw(f,c,d)}};
z.e.eG=function(a){if(1!==this.Xm){var b=this.NX.rh;b.Gi(!1);LK(b,b.sm);z.kb(a,{direction:"new",Yb:z.n});this.oG(a)}};z.e.kR=function(a){z.sG(this);a.stream.jn(a.direction);var b=this.d.Mb.tl(a.direction,!0),c=(0,z.t)(function(b){a.Yb();this.Te(a.stream,b)},this);z.rG(this,b,c,a.zj)};z.e.oG=function(a){this.d.J.hi=null;var b=z.uG(this,1);z.Wv(this.d.Mb);b.jn(a.direction);var c=z.Vv(this.d.Mb,a.direction),d=(0,z.t)(function(c){a.Yb();this.Te(b,c)},this);z.rG(this,c,d,a.zj)};
z.e.qT=function(a){var b=z.uG(this,3),c=this.d.Mb.Rh("likes");z.rG(this,c,(0,z.t)(function(c){a.Yb();z.hb(c)?z.Ux(b):this.Te(b,c)},this))};z.e.pT=function(a){var b=z.uG(this,4),c=this.d.Mb.Vh();z.rG(this,c,(0,z.t)(function(c){a.Yb();z.hb(c)?z.Ux(b):this.Te(b,c)},this))};z.v(YK,z.Rs);z.e=YK.prototype;z.e.c=null;z.e.h=function(){YK.b.h.call(this);this.wt.q();this.ID.q();this.Tb.ba&&this.Tb.q();this.Vf&&this.Vf.q();delete this.Vf};z.e.Il=function(a){YK.b.Il.call(this,a);this.wt=new XK(this.d);this.wt.handle(a);this.ID=new z.nG(this.d);this.ID.handle(a)};z.e.Fz=function(){this.d.Ji.stop()};z.e.UX=function(){this.d.Sl.stop()};z.e.fk=function(){this.d.Ji.start()};z.e.RX=function(){this.d.Sl.start()};
z.e.ra=function(){this.Vf&&this.Vf.q();this.Tb.ra(this.c);this.d.Lb.send(z.Vn("Load"));var a=z.Ts(window.location,"reply_editor");if("object"===typeof window.Livefyre&&window.Livefyre.pO)z.Xs(this,a);else{var b=z.Us(this);this.Tb.dh(b,a)}this.d.U.N("render_complete",this.c)};z.v(ZK,z.Fn);ZK.prototype.$C=FK.C();ZK.prototype.h=function(){ZK.b.h.call(this);this.stop();delete this.J;delete this.ha;$K(this);z.Kn(this);this.yj&&(this.yj.q(),delete this.yj)};ZK.prototype.Nz=function(){this.stop();$K(this);ZK.b.Nz.call(this)};z.jg.main.Nh.ia(ZK);})(fyre.conv);
