(function(){
var g="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,h="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};function k(){k=function(){};g.Symbol||(g.Symbol=m)}var n=0;function m(a){return"jscomp_symbol_"+(a||"")+n++}
function q(){k();var a=g.Symbol.iterator;a||(a=g.Symbol.iterator=g.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&h(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return r(this)}});q=function(){}}function r(a){var c=0;return t(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})}function t(a){q();a={next:a};a[g.Symbol.iterator]=function(){return this};return a}function u(a){q();var c=a[Symbol.iterator];return c?c.call(a):r(a)}
function v(a,c){if(c){var b=g;a=a.split(".");for(var d=0;d<a.length-1;d++){var f=a[d];f in b||(b[f]={});b=b[f]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&h(b,a,{configurable:!0,writable:!0,value:c})}}
v("Promise",function(a){function c(a){this.b=0;this.g=void 0;this.a=[];var b=this.f();try{a(b.resolve,b.reject)}catch(y){b.reject(y)}}function b(){this.a=null}function d(a){return a instanceof c?a:new c(function(b){b(a)})}if(a)return a;b.prototype.b=function(a){this.a||(this.a=[],this.c());this.a.push(a)};b.prototype.c=function(){var a=this;this.f(function(){a.h()})};var f=g.setTimeout;b.prototype.f=function(a){f(a,0)};b.prototype.h=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=
0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(z){this.g(z)}}}this.a=null};b.prototype.g=function(a){this.f(function(){throw a;})};c.prototype.f=function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=!1;return{resolve:a(this.o),reject:a(this.c)}};c.prototype.o=function(a){if(a===this)this.c(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof c)this.s(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=
!1}b?this.l(a):this.h(a)}};c.prototype.l=function(a){var b=void 0;try{b=a.then}catch(y){this.c(y);return}"function"==typeof b?this.v(b,a):this.h(a)};c.prototype.c=function(a){this.i(2,a)};c.prototype.h=function(a){this.i(1,a)};c.prototype.i=function(a,b){if(0!=this.b)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.b);this.b=a;this.g=b;this.j()};c.prototype.j=function(){if(this.a){for(var a=this.a,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.a=null}};var e=new b;c.prototype.s=
function(a){var b=this.f();a.L(b.resolve,b.reject)};c.prototype.v=function(a,b){var c=this.f();try{a.call(b,c.resolve,c.reject)}catch(z){c.reject(z)}};c.prototype.then=function(a,b){function d(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(T){f(T)}}:b}var e,f,p=new c(function(a,b){e=a;f=b});this.L(d(a,e),d(b,f));return p};c.prototype.catch=function(a){return this.then(void 0,a)};c.prototype.L=function(a,b){function c(){switch(d.b){case 1:a(d.g);break;case 2:b(d.g);break;default:throw Error("Unexpected state: "+
d.b);}}var d=this;this.a?this.a.push(function(){e.b(c)}):e.b(c)};c.resolve=d;c.reject=function(a){return new c(function(b,c){c(a)})};c.race=function(a){return new c(function(b,c){for(var e=u(a),f=e.next();!f.done;f=e.next())d(f.value).L(b,c)})};c.all=function(a){var b=u(a),e=b.next();return e.done?d([]):new c(function(a,c){function f(b){return function(c){p[b]=c;l--;l||a(p)}}var p=[],l=0;do p.push(void 0),l++,d(e.value).L(f(p.length-1),c),e=b.next();while(!e.done)})};return c});
v("Object.is",function(a){return a?a:function(a,b){return a===b?0!==a||1/a===1/b:a!==a&&b!==b}});v("String.prototype.includes",function(a){return a?a:function(a,b){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(a instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==(this+"").indexOf(a,b||0)}});
var w=window.BEACON_SIZE?window.BEACON_SIZE:9,x=window.BEACON_ZINDEX?window.BEACON_ZINDEX:-9999,A=window.BEACON_OPACITY?window.BEACON_OPACITY:.01;k();var B=Symbol("Beacons");k();var C=Symbol("Beacons");function D(a){if(a!==C)throw"Beacons is a singleton: Cannot construct directly. Use 'Observer.instance'";this.$=((new Date).getTime()+""+Math.floor(1E7*Math.random())).substr(0,16)}
D.prototype.ba=function(a,c){var b=this;this.f=a;this.A=c;this.g=[];this.a=Array(14);this.da=0;this.i=1;this.o=2;this.s=3;this.j=4;this.l=5;this.K=6;this.T=7;this.I=8;this.J=9;this.N=10;this.P=11;this.v=12;this.H=13;E(this,!0);return new Promise(function(a,c){for(var d=[],f=0;f<b.h.length;f++){var l=new F(b.f,f,b.$,b.h[f],b.ea.bind(b));b.g.push(l);d.push(G(l))}Promise.all(d).then(b.V.bind(b)).then(a).catch(c)})};
function E(a,c){c=void 0===c?!1:c;a.U=a.f.getBoundingClientRect();a.b=a.U.width;a.c=a.U.height;var b=Math.sqrt(2),d=a.b/(1+b),f=a.c/(1+b),e=a.b/b,b=a.c/b;a.h=[{name:"CONTROL",left:c?a.b/2:-1E4,top:c?a.b/2:-1E4},{name:"CENTER",left:(a.b-w)/2,top:(a.c-w)/2},{name:"OUTER_TOP_LEFT",left:1,top:1},{name:"OUTER_TOP_RIGHT",left:a.b-w-1,top:1},{name:"OUTER_BOTTOM_LEFT",left:1,top:a.c-w-1},{name:"OUTER_BOTTOM_RIGHT",left:a.b-w-1,top:a.c-w-1},{name:"MIDDLE_TOP_LEFT",left:(a.b-e-w)/2,top:(a.c-b-w)/2},{name:"MIDDLE_TOP_RIGHT",
left:(a.b+e-w)/2,top:(a.c-b-w)/2},{name:"MIDDLE_BOTTOM_LEFT",left:(a.b-e-w)/2,top:(a.c+b-w)/2},{name:"MIDDLE_BOTTOM_RIGHT",left:(a.b+e-w)/2,top:(a.c+b-w)/2},{name:"INNER_TOP_LEFT",left:(a.b-d-w)/2,top:(a.c-f-w)/2},{name:"INNER_TOP_RIGHT",left:(a.b+d-w)/2,top:(a.c-f-w)/2},{name:"INNER_BOTTOM_LEFT",left:(a.b-d-w)/2,top:(a.c+f-w)/2},{name:"INNER_BOTTOM_RIGHT",left:(a.b+d-w)/2,top:(a.c+f-w)/2}]}
D.prototype.V=function(){E(this);for(var a=0;a<this.h.length;a++){var c=this.g[a].u,b=this.h[a];c.style.top=b.top+"px";c.style.left=b.left+"px"}};D.prototype.ea=function(a){switch(a.type){case "ready":this.g[a.index].resolve();this.a[a.index]=a.state;break;case "inview":this.a[a.index]=!0;break;case "outofview":this.a[a.index]=!1}};
D.prototype.aa=function(){var a=0,c=0,b=0,d=0;if(this.a[this.da])return"unmeasurable";for(var f=this.g.length-1,e=1;e<this.a.length;e++)if(this.a[e])switch(a++,e){case this.o:case this.s:case this.j:case this.l:c++;break;case this.K:case this.T:case this.I:case this.J:b++;break;case this.N:case this.P:case this.v:case this.H:d++}if(a===f)b="viewable";else if(100==this.A)b="unviewable";else{a:{d=[[this.o,this.K,this.N,this.i,this.H,this.J,this.l],[this.s,this.T,this.P,this.i,this.v,this.I,this.j]];
for(f=0;2>f;f++)for(var e=d[f],p=c=0;p<e.length;p++)if(a=this.a[e[p]],!0===a&&!c)c++;else if(!1===a&&1==c)c++;else if(!0===a&&2==c){a=!0;break a}a=!1}b=a?"unmeasurable":!0===this.a[this.i]&&(!0===this.a[this.o]&&!0===this.a[this.s]||!0===this.a[this.o]&&!0===this.a[this.j]||!0===this.a[this.s]&&!0===this.a[this.l]||!0===this.a[this.j]&&!0===this.a[this.l])||!0===this.a[this.i]&&4==b?"viewable":"unviewable"}return b};D.prototype.ca=function(){this.g.forEach(function(a){clearInterval(a.ga);a.u.parentNode.removeChild(a.u)})};
g.Object.defineProperties(D,{a:{configurable:!0,enumerable:!0,get:function(){this[B]||(this[B]=new D(C));return this[B]}}});function F(a,c,b,d,f){this.h=a;this.index=c;this.g="frame_"+c+b;this.a="beaconProcess_"+c+b;this.c=d;this.resolve=null;this.b="number"===typeof window.mozPaintCount;this.f=f;this.u=document.createElement("iframe")}
function G(a){var c="",c=a.b?"parent.window."+a.a+"()":"window.frameCount = 0;var render = function(timestamp){   window.frameCount++;    requestAnimationFrame(render.bind(this));};render();parent.window."+a.a+"()";a.i="<html><head></head><body onload='"+c+"'></body></html>";H(a);return new Promise(function(b){a.resolve=b;a.h.appendChild(a.u);a.u.id=a.g;a.u.style.cssText="position:absolute;border:none;z-index:"+x+";opacity:"+A+";width:"+w+"px;height:"+w+"px;top:"+a.c.top+"px;left:"+a.c.left+"px;";
a.u.contentWindow.document.open().write(a.i);a.u.contentWindow.document.close()})}
function H(a){window[a.a]=function(){var c=a.u.contentWindow,b=a.b?0:4,d=a.b?"mozPaintCount":"frameCount",f=!1,e=!1,p=c[d];a.ga=setInterval(function(){var l=c[d];!e&&l-p>b?(e=!0,a.f({type:"inview",index:a.index},"*")):e&&l-p<=b&&(e=!1,a.f({type:"outofview",index:a.index}));p=l;l=(16+Math.round(52*Math.random())).toString(16);c.document.body.style.background=!0===e?"#"+l+"ff"+l:"#ff"+l+l;!1===f&&(a.f({type:"ready",index:a.index,state:e}),f=!0)},200)}};k();var I=Symbol("Geometry");k();var J=Symbol("Geometry");
function K(a){var c=this;if(a!==J)throw"Geometry is a singleton: Cannot construct directly. Use 'Geometry.instance'";this.i=function(){for(var a=c.a(window),d=a.w,f=window,e;f!=window.top;)f=f.parent,e=c.a(f),e.w<d&&(d=e.w,a=e);return a};this.a=function(a){var b={width:Infinity,height:Infinity,w:Infinity};!isNaN(a.document.body.clientWidth)&&0<a.document.body.clientWidth&&(b.width=a.document.body.clientWidth);!isNaN(a.document.body.clientHeight)&&0<a.document.body.clientHeight&&(b.height=a.document.body.clientHeight);
a.document.documentElement&&a.document.documentElement.clientWidth&&!isNaN(a.document.documentElement.clientWidth)&&(b.width=a.document.documentElement.clientWidth);a.document.documentElement&&a.document.documentElement.clientHeight&&!isNaN(a.document.documentElement.clientHeight)&&(b.height=a.document.documentElement.clientHeight);a.innerWidth&&!isNaN(a.innerWidth)&&(b.width=Math.min(b.width,a.innerWidth));a.innerHeight&&!isNaN(a.innerHeight)&&(b.height=Math.min(b.height,a.innerHeight));b.w=b.height*
b.width;return b};this.b=function(a,d){var b=d.parent,e={width:0,height:0,left:0,right:0,top:0,bottom:0};a&&(e=c.c(a,d),e.width=e.right-e.left,e.height=e.bottom-e.top,d!=b&&(d=c.b(d.frameElement,b),d.bottom<e.bottom&&(d.bottom<e.top&&(e.top=d.bottom),e.bottom=d.bottom),d.right<e.right&&(d.right<e.left&&(e.left=d.right),e.right=d.right),e.width=e.right-e.left,e.height=e.bottom-e.top));return e};this.c=function(a,d){var b=d.parent,e={left:0,right:0,top:0,bottom:0};a&&(a=a.getBoundingClientRect(),d!=
b?e=c.c(d.frameElement,b):e={left:a.left+e.left,right:a.right+e.left,top:a.top+e.top,bottom:a.bottom+e.top});return e}}K.prototype.h=function(a){this.f=a};function L(){try{if(window.top==window)return!0;for(var a=window;a.parent!=a;){if(a.parent.document.domain!=a.document.domain)return!1;a=a.parent}return!0}catch(c){}return!1}
K.prototype.g=function(a){var c=this.i();if(Infinity==c.w)return{error:"unmeasurable"};var b=this.f.getBoundingClientRect(),b=b.width*b.height;if(c.w/b<a)a=Math.floor(100*c.w/b);else{var d=this.a(window.top);a=this.b(this.f,window);a.bottom>d.height&&(a.height-=a.bottom-d.height);0>a.top&&(a.height+=a.top);0>a.left&&(a.width+=a.left);a.right>d.width&&(a.width-=a.right-d.width);a=Math.floor(100*a.width*a.height/b)}return{clientWidth:d.width,clientHeight:d.height,W:a}};
g.Object.defineProperties(K,{a:{configurable:!0,enumerable:!0,get:function(){this[I]||(this[I]=new K(J));return this[I]}}});k();var M=Symbol("Observer");k();var N=Symbol("Observer");function O(a){if(a!==N)throw"Observer is a singleton: Cannot construct directly. Use 'Observer.instance'";this.a=0}O.prototype.f=function(a){this.target=a;this.b=new window.IntersectionObserver(this.h.bind(this),{threshold:[0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1]});this.b.observe(this.target)};O.prototype.c=function(){this.b.unobserve(this.target)};O.prototype.h=function(a){var c=this;0==a.length?this.a=0:a.forEach(function(a){c.a=a.intersectionRatio})};
O.prototype.g=function(){return this.a};g.Object.defineProperties(O,{a:{configurable:!0,enumerable:!0,get:function(){this[M]||(this[M]=new O(N));return this[M]}}});k();var P=Symbol("ViewabilityModel");k();var Q=Symbol("ViewabilityModel");function R(a){if(a!==Q)throw"ViewabilityModel is a singleton: Cannot construct directly. Use 'ViewabilityModel.instance'";this.fa=5;this.ka=1;this.A=this.Z=-1;this.a=R.a.MRC}
g.Object.defineProperties(R.prototype,{m:{configurable:!0,enumerable:!0,set:function(a){a&&a in R.a&&(this.a=R.a[a])},get:function(){return this.a}},M:{configurable:!0,enumerable:!0,get:function(){return this.m.M}},S:{configurable:!0,enumerable:!0,get:function(){return this.m.S}},G:{configurable:!0,enumerable:!0,get:function(){return this.m.G}},O:{configurable:!0,enumerable:!0,get:function(){return this.m.O}},D:{configurable:!0,enumerable:!0,get:function(){return this.m.D}},R:{configurable:!0,enumerable:!0,
get:function(){return this.m.R}}});g.Object.defineProperties(R,{b:{configurable:!0,enumerable:!0,get:function(){this[P]||(this[P]=new R(Q));return this[P]}},a:{configurable:!0,enumerable:!0,get:function(){return{GROUPM:{M:100,S:!0,G:200,O:!1,D:null,R:50},MRC:{M:50,S:!1,G:200,O:!0,D:2,R:null}}}},c:{configurable:!0,enumerable:!0,get:function(){return"MRC"}},f:{configurable:!0,enumerable:!0,get:function(){return"GROUPM"}}});k();var S=Symbol("ViewabilityControl");k();var U=Symbol("ViewabilityControl");
function V(a){if(a!==U)throw"ViewabilityControl is a singleton: Cannot construct directly. Use 'ViewabilityControl.instance'";this.a="NONE";this.l=NaN;this.P=this.v=0;this.i=this.g=this.s=!1;this.c=0;this.h="err";this.f=this.j=null;window.addEventListener("resize",this.H.bind(this),!1)}
function aa(a,c,b){var d=V.a;d.f=c;d.b=a;d.K=b;new Promise(function(a){if("function"===typeof window.IntersectionObserver)O.a.f.call(O.a,d.f),d.a=W.b,a(!0);else{var b=X.a;b.ha&&"number"===typeof window.mozPaintCount||b.ia&&"function"===typeof window.requestAnimationFrame?(d.a=W.a,D.a.ba.call(D.a,d.f,d.b.A).then(a.bind(null,!0)).catch(a.bind(null,!1))):L()?(K.a.h.call(K.a,d.f),d.a=W.c,a(!0)):(d.o.call(d,"ifr"),a(!1))}})}V.prototype.H=function(){switch(this.a){case W.a:D.a.V.call(D.a)}};
function ba(a){document.fullscreenElement==a.f&&(a.j={X:a.a,Y:a.c},a.a=W.f);["webkitbeginfullscreen","webkitendfullscreen","webkitfullscreenchange","mozfullscreenchange","fullscreenchange"].forEach(function(c){a.f.addEventListener(c,function(){document.fullscreenElement==a.f?(a.j={X:a.a,Y:a.c},a.a=W.f):(a.a=a.j.X,a.c=a.j.Y,a.j=null)})})}
function ca(a){var c;if(!(c=document.hidden)){var b=window.getComputedStyle(a.f);c=b.getPropertyValue("visibility");b=b.getPropertyValue("display");c=!("hidden"!==c&&"none"!==b)}if(c)return a.h="f";switch(a.a){case W.f:return a.g=!0,a.i=!1,a.c=100,a.h="t";case W.b:return a.c=Math.round(100*O.a.g.call(O.a)),a.g=a.c>=a.b.A,a.i=!1,a.h=a.g?"t":"f";case W.a:return c=D.a.aa.call(D.a),a.g="viewable"===c,a.i="unmeasurable"===c,a.c=0,a.h=a.g?"t":a.i?"err":"f";case W.c:return c=K.a.g.call(K.a,a.b.A/100),a.g=
c.W>=a.b.A,a.i="unmeasurable"===c.error,a.c=c.W,a.h=a.g?"t":a.i?"ifr":"f"}return"err"}V.prototype.N=function(){var a=ca(this);"t"==a?++this.v>=this.b.Z&&Y(this):"f"==a?this.b.m.O&&(this.v=0):++this.P>this.b.fa&&Y(this)};function Y(a){a.s||(a.s=!0,a.o.call(a,a.h))}
V.prototype.o=function(a){if("t:err:ifr".includes(a)){try{var c=X.a;var b=[X.v,c.code+":"+c.version,"IF:"+X.b].join(":::")}catch(d){b="error in ViewabilityEnv::getEnvStr()"}b={vwbl:this.h,vver:this.b.ka,vpct:this.c,venv:b,ifr:X.b!==X.f};b.vwbl=a;this.K(b)}else void 0};V.prototype.I=function(){this.a===W.b&&O.a.f.call(O.a,this.f);ba(this);Z(this);this.l=setInterval(this.N.bind(this),this.b.m.G)};
V.prototype.J=function(){window.removeEventListener("resize",this.H);Z(this);switch(this.a){case W.b:O.a.b&&O.a.c.call(O.a);break;case W.a:D.a.ca.call(D.a)}};function Z(a){isNaN(a.l)||(clearInterval(a.l),a.l=NaN)}g.Object.defineProperties(V,{a:{configurable:!0,enumerable:!0,get:function(){this[S]||(this[S]=new V(U));return this[S]}}});function W(){}
g.Object.defineProperties(W,{b:{configurable:!0,enumerable:!0,get:function(){return"INTERSECTION_OBSERVER"}},a:{configurable:!0,enumerable:!0,get:function(){return"IFRAME_BEACONS"}},c:{configurable:!0,enumerable:!0,get:function(){return"BROWSER_GEOMETRY"}},f:{configurable:!0,enumerable:!0,get:function(){return"FULL_SCREEN_OVERRIDE"}}});function X(){}
g.Object.defineProperties(X,{c:{configurable:!0,enumerable:!0,get:function(){return"CH"}},h:{configurable:!0,enumerable:!0,get:function(){return"FF"}},l:{configurable:!0,enumerable:!0,get:function(){return"SF"}},i:{configurable:!0,enumerable:!0,get:function(){return"IE"}},j:{configurable:!0,enumerable:!0,get:function(){return"OP"}},g:{configurable:!0,enumerable:!0,get:function(){return"ME"}},f:{configurable:!0,enumerable:!0,get:function(){return"F0"}},o:{configurable:!0,enumerable:!0,get:function(){return"FS"}},
s:{configurable:!0,enumerable:!0,get:function(){return"FX"}},b:{configurable:!0,enumerable:!0,get:function(){try{if(window.top==window)return X.f;if(window.top.document.domain==window.document.domain)return X.o}catch(a){}return X.s}},a:{configurable:!0,enumerable:!0,get:function(){a:{for(var a=[{B:"Edge",C:"Edge.([0-9]+)",name:"MicroSoftEdge",code:"ME"},{B:"Chrome",C:"Chrome.([0-9]+)",name:"chrome",code:"CH"},{ja:navigator.vendor,B:"Apple",C:"(?:Version|Safari).([1-9]?\\d)[^0-9]",name:"safari",code:"SF"},
{B:"Opera",C:"Version.([0-9]+)",name:"opera",code:"OP"},{B:"Firefox",C:"Firefox.([0-9]+)",name:"firefox",code:"FF"},{B:"MSIE|Trident.7",C:"(?:MSIE| rv).([0-9]+)",name:"internet explorer",code:"IE"}],c=0;c<a.length;c++)if((new RegExp(a[c].B)).test(a[c].ja||navigator.userAgent)){var b=new RegExp(".*"+a[c].C+".*");a={name:a[c].name,code:a[c].code};a.version=navigator.userAgent.replace(b,"$1");b=a;break a}b=void 0}b=b||{name:"Unknown",code:"??",version:0};b.la=b.code===X.c;b.ia=b.code===X.l;b.ha=b.code===
X.h;b.na=b.code===X.i;b.oa=b.code===X.j;b.ma=b.code===X.g;return b}},v:{configurable:!0,enumerable:!0,get:function(){[{test:"Mac",F:"Mac"},{test:"Win",F:"Win"},{test:"i(Phone|Pad)",F:"iOS"},{test:"Linux arm",F:"Android"},{test:"Linux",F:"Linux"}].forEach(function(a){if((new RegExp(a.test)).test(navigator.platform))return a.F});return"Other"}}});
window.TMViewability=function(a){var c=a.targetElement,b=a.vimpCallback;a=a.viewabilityStandard;var d=R.b;d.m=void 0===a?"MRC":a;d.A=d.m.M;null!==d.m.D&&(d.Z=Math.ceil(1E3*d.m.D/d.m.G));aa(d,c,b);return{start:V.a.I.bind(V.a),stop:V.a.J.bind(V.a)}};
}).call(this)

//# sourceMappingURL=tm_viewability.js.map
